# Generated by Django 3.1 on 2020-09-15 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mootext',
            name='text',
            field=models.TextField(max_length=50),
        ),
    ]
